In [11]:
# Q1: Basic Operations

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("Original:", arr)
print("+2:", arr + 2)
print("*3:", arr * 3)
print("/2:", arr / 2)

Original: [1 2 3 4 5]
+2: [3 4 5 6 7]
*3: [ 3  6  9 12 15]
/2: [0.5 1.  1.5 2.  2.5]


In [10]:
# Q2: Array Manipulations

arr2 = np.array([1, 2, 3, 6, 4, 5])
print("Reversed:", arr2[::-1])
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])
most_x = np.bincount(x).argmax()
most_y = np.bincount(y).argmax()
print("Most in x:", most_x, "at", np.where(x == most_x)[0])
print("Most in y:", most_y, "at", np.where(y == most_y)[0])

Reversed: [5 4 6 3 2 1]
Most in x: 1 at [0 5 7 8 9]
Most in y: 1 at [0 1 2]


In [9]:
# Q3: 2D Array Indexing

arr3 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("1st row, 2nd col:", arr3[0, 1])
print("3rd row, 1st col:", arr3[2, 0])

1st row, 2nd col: 20
3rd row, 1st col: 70


In [8]:
# Q4: Linspace Array

vinayak = np.linspace(10, 100, 25)
print("Dims:", vinayak.ndim, "Shape:", vinayak.shape, "Total:", vinayak.size)
print("Type:", vinayak.dtype, "Bytes:", vinayak.nbytes)
reshaped_vinayak = vinayak.reshape(5, 5)
print("Reshaped:", reshaped_vinayak)
print("Transpose using .T:", vinayak.T)

Dims: 1 Shape: (25,) Total: 25
Type: float64 Bytes: 200
Reshaped: [[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]
Transpose using .T: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [7]:
# Q5: 2D Array Operations

ucs420_vinayak = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Mean:", np.mean(ucs420_vinayak), "Median:", np.median(ucs420_vinayak))
print("Max:", np.max(ucs420_vinayak), "Min:", np.min(ucs420_vinayak))
print("Unique:", np.unique(ucs420_vinayak))
reshaped_ucs420_vinayak = ucs420_vinayak.reshape(4, 3)

print("Reshaped 4x3:", reshaped_ucs420_vinayak)

resized_ucs420_vinayak = np.resize(ucs420_vinayak, (2, 3))
print("Resized 2x3:", resized_ucs420_vinayak)


Mean: 43.333333333333336 Median: 37.5
Max: 90 Min: 10
Unique: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped 4x3: [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized 2x3: [[10 20 30]
 [40 50 60]]
